package packet

const (
	SOCK_BUFFER = 4096
)

const (
	PACKET_ID_REGISTER_REQUEST  = 1
	PACKET_ID_REGISTER_RESPONSE = 2
	PACKET_ID_LOGIN_REQUEST     = 3
	PACKET_ID_LOGIN_RESPONSE    = 4
)

const (
	ERROR_ID_NONE              = 1000
	ERROR_ID_INVALID_REQUEST   = 1001
	ERROR_ID_ALREADY_ACCOUNT   = 1002
	ERROR_ID_INVALID_PASSWORD  = 1003
	ERROR_ID_NOT_EXIST_ACCOUNT = 1004
	ERROR_ID_INVALID_EMAIL     = 1005
)
